name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Run make compare
        run: make compare
      - name: Publish to crates.io
        if: success()
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked --no-verify
